development:
  adapter: async

test:
  adapter: async

production: &production
  adapter: redis
  :url: redis://h:pf1ccab29958a936b14d20de3cc0abede8f83b96c99f900688731577e1a18c109@ec2-34-192-25-148.compute-1.amazonaws.com:49629
  :host: @ec2-34-192-25-148.compute-1.amazonaws.com
  :port: 49629
  :inline: true
  :timeout: 1
  channel_prefix: TwelveStep_production
